adspower:
  api_key: '686ba74a10897ff4dead5376be8baf2900338fe06b755681'
  api_url: http://local.adspower.net:50325
  default_group_id: '8631877'
bot:
  max_session_duration: 1800
  min_session_duration: 300
  mouse_speed: human
  typing_max_delay: 0.2
  typing_min_delay: 0.05
  typo_chance: 0.02
log_file: logs/bot.log
log_level: INFO
max_concurrent_profiles: 5
proxy:
  countries:
  - US
  - UK
  - DE
  - CA
  host: geo.iproyal.com
  password: ''
  port: 12321
  provider: iproyal
  sticky_duration: 600
  username: ''
